### ISSUE TITLE
can we use 'sp-requests' library in Angular 6/7 with post requests? Please provide an example with Create/Update requests

### ISSUE THREAD

**Issue by Gopinath83** [s-KaiNet/sp-request#14]

**Comment by s-KaiNet** [comment]
Hi Gopinath, 
you can't use it with angular, because `sp-request` is nodejs only module and doesn't work in a browser environment. For your needs consider [sp-rest-proxy](https://github.com/koltyakov/sp-rest-proxy) module. Additionally, if you want to talk to SharePoint from an Angular app, you should implement an authentication strategy on your own.
